plugins {
    id 'com.android.application'
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "io.iicebear.crimson.fps"
        minSdk 28
        targetSdk 34
        versionCode 20
        versionName "Stable 30/12/25"
        namespace 'io.iicebear.crimson.fps'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    dependenciesInfo.includeInApk false
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    compileOnly fileTree(dir: 'libs/compile_only', include: ['*.jar'])
}