plugins {
    id 'com.android.application'
}

def ks = rootProject.file('release.keystore')
def sp = new Properties()
def spFile = rootProject.file('local.properties')
if (spFile.exists()) sp.load(spFile.newInputStream())

android {
    compileSdk 34

    defaultConfig {
        applicationId "io.iicebear.crimson.fps"
        minSdk 28
        targetSdk 34
        versionCode 20
        versionName "Stable 30/12/25"
        namespace 'io.iicebear.crimson.fps'
    }

    signingConfigs {
        release {
            storeFile ks
            storePassword sp.getProperty('signing.storePassword', '')
            keyAlias sp.getProperty('signing.keyAlias', '')
            keyPassword sp.getProperty('signing.keyPassword', '')
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig ks.exists() ? signingConfigs.release : null
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    dependenciesInfo.includeInApk false
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    compileOnly fileTree(dir: 'libs/compile_only', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
}